// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- Message Types ----
type ListNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeReq) Reset() {
	*x = ListNodeReq{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeReq) ProtoMessage() {}

func (x *ListNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeReq.ProtoReflect.Descriptor instead.
func (*ListNodeReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *ListNodeReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListNodeReq) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListNodeReq) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	NetDelay      int32                  `protobuf:"varint,3,opt,name=net_delay,json=netDelay,proto3" json:"net_delay,omitempty"`
	BindUser      string                 `protobuf:"bytes,4,opt,name=bind_user,json=bindUser,proto3" json:"bind_user,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Node) GetNetDelay() int32 {
	if x != nil {
		return x.NetDelay
	}
	return 0
}

func (x *Node) GetBindUser() string {
	if x != nil {
		return x.BindUser
	}
	return ""
}

func (x *Node) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ListNodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeResp) Reset() {
	*x = ListNodeResp{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeResp) ProtoMessage() {}

func (x *ListNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeResp.ProtoReflect.Descriptor instead.
func (*ListNodeResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *ListNodeResp) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodeResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. auto mode, 2. manual mode, 3. Timed switching点击并应用
	Mode   int32  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// mode=Timed
	// If >0, switch every N minutes
	IntervalMinutes int32 `protobuf:"varint,3,opt,name=interval_minutes,json=intervalMinutes,proto3" json:"interval_minutes,omitempty"`
	// mode=Timed
	// If interval_minutes=0, trigger at specific UTC minutes of day
	UtcMinuteOfDay int32 `protobuf:"varint,4,opt,name=utc_minute_of_day,json=utcMinuteOfDay,proto3" json:"utc_minute_of_day,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Route) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Route) GetIntervalMinutes() int32 {
	if x != nil {
		return x.IntervalMinutes
	}
	return 0
}

func (x *Route) GetUtcMinuteOfDay() int32 {
	if x != nil {
		return x.UtcMinuteOfDay
	}
	return 0
}

type TrafficLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalTraffic  int64                  `protobuf:"varint,3,opt,name=total_traffic,json=totalTraffic,proto3" json:"total_traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficLimit) Reset() {
	*x = TrafficLimit{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficLimit) ProtoMessage() {}

func (x *TrafficLimit) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficLimit.ProtoReflect.Descriptor instead.
func (*TrafficLimit) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficLimit) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TrafficLimit) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TrafficLimit) GetTotalTraffic() int64 {
	if x != nil {
		return x.TotalTraffic
	}
	return 0
}

type CreateUserReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserName          string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password          string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TrafficLimit      *TrafficLimit          `protobuf:"bytes,3,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	Route             *Route                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	UploadRateLimite  int64                  `protobuf:"varint,5,opt,name=upload_rate_limite,json=uploadRateLimite,proto3" json:"upload_rate_limite,omitempty"`
	DownloadRateLimit int64                  `protobuf:"varint,6,opt,name=download_rate_limit,json=downloadRateLimit,proto3" json:"download_rate_limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetTrafficLimit() *TrafficLimit {
	if x != nil {
		return x.TrafficLimit
	}
	return nil
}

func (x *CreateUserReq) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *CreateUserReq) GetUploadRateLimite() int64 {
	if x != nil {
		return x.UploadRateLimite
	}
	return 0
}

func (x *CreateUserReq) GetDownloadRateLimit() int64 {
	if x != nil {
		return x.DownloadRateLimit
	}
	return 0
}

type CreateUserResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserName          string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrafficLimit      *TrafficLimit          `protobuf:"bytes,2,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	Route             *Route                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	NodeIp            string                 `protobuf:"bytes,4,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	UploadRateLimite  int64                  `protobuf:"varint,5,opt,name=upload_rate_limite,json=uploadRateLimite,proto3" json:"upload_rate_limite,omitempty"`
	DownloadRateLimit int64                  `protobuf:"varint,6,opt,name=download_rate_limit,json=downloadRateLimit,proto3" json:"download_rate_limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserResp) GetTrafficLimit() *TrafficLimit {
	if x != nil {
		return x.TrafficLimit
	}
	return nil
}

func (x *CreateUserResp) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *CreateUserResp) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *CreateUserResp) GetUploadRateLimite() int64 {
	if x != nil {
		return x.UploadRateLimite
	}
	return 0
}

func (x *CreateUserResp) GetDownloadRateLimit() int64 {
	if x != nil {
		return x.DownloadRateLimit
	}
	return 0
}

type UserOperationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOperationResp) Reset() {
	*x = UserOperationResp{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOperationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOperationResp) ProtoMessage() {}

func (x *UserOperationResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOperationResp.ProtoReflect.Descriptor instead.
func (*UserOperationResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *UserOperationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserOperationResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type ModifyUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyUserPasswordReq) Reset() {
	*x = ModifyUserPasswordReq{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserPasswordReq) ProtoMessage() {}

func (x *ModifyUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserPasswordReq.ProtoReflect.Descriptor instead.
func (*ModifyUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyUserPasswordReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ModifyUserPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ModifyUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrafficLimit  *TrafficLimit          `protobuf:"bytes,2,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	Route         *Route                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyUserReq) Reset() {
	*x = ModifyUserReq{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserReq) ProtoMessage() {}

func (x *ModifyUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserReq.ProtoReflect.Descriptor instead.
func (*ModifyUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ModifyUserReq) GetTrafficLimit() *TrafficLimit {
	if x != nil {
		return x.TrafficLimit
	}
	return nil
}

func (x *ModifyUserReq) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type SwitchUserRouteNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchUserRouteNodeReq) Reset() {
	*x = SwitchUserRouteNodeReq{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchUserRouteNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchUserRouteNodeReq) ProtoMessage() {}

func (x *SwitchUserRouteNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchUserRouteNodeReq.ProtoReflect.Descriptor instead.
func (*SwitchUserRouteNodeReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *SwitchUserRouteNodeReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SwitchUserRouteNodeReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type StartOrStopUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOrStopUserReq) Reset() {
	*x = StartOrStopUserReq{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOrStopUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOrStopUserReq) ProtoMessage() {}

func (x *StartOrStopUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOrStopUserReq.ProtoReflect.Descriptor instead.
func (*StartOrStopUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *StartOrStopUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *StartOrStopUserReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserName            string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrafficLimit        *TrafficLimit          `protobuf:"bytes,2,opt,name=traffic_limit,json=trafficLimit,proto3" json:"traffic_limit,omitempty"`
	Route               *Route                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	NodeIp              string                 `protobuf:"bytes,4,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	NodeOnline          bool                   `protobuf:"varint,5,opt,name=node_online,json=nodeOnline,proto3" json:"node_online,omitempty"`
	CurrentTraffic      int64                  `protobuf:"varint,6,opt,name=current_traffic,json=currentTraffic,proto3" json:"current_traffic,omitempty"`
	Off                 bool                   `protobuf:"varint,7,opt,name=off,proto3" json:"off,omitempty"`
	UploadRateLimite    int64                  `protobuf:"varint,8,opt,name=upload_rate_limite,json=uploadRateLimite,proto3" json:"upload_rate_limite,omitempty"`
	DownloadRateLimit   int64                  `protobuf:"varint,9,opt,name=download_rate_limit,json=downloadRateLimit,proto3" json:"download_rate_limit,omitempty"`
	LastRouteSwitchTime int64                  `protobuf:"varint,10,opt,name=last_route_switch_time,json=lastRouteSwitchTime,proto3" json:"last_route_switch_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetTrafficLimit() *TrafficLimit {
	if x != nil {
		return x.TrafficLimit
	}
	return nil
}

func (x *User) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *User) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *User) GetNodeOnline() bool {
	if x != nil {
		return x.NodeOnline
	}
	return false
}

func (x *User) GetCurrentTraffic() int64 {
	if x != nil {
		return x.CurrentTraffic
	}
	return 0
}

func (x *User) GetOff() bool {
	if x != nil {
		return x.Off
	}
	return false
}

func (x *User) GetUploadRateLimite() int64 {
	if x != nil {
		return x.UploadRateLimite
	}
	return 0
}

func (x *User) GetDownloadRateLimit() int64 {
	if x != nil {
		return x.DownloadRateLimit
	}
	return 0
}

func (x *User) GetLastRouteSwitchTime() int64 {
	if x != nil {
		return x.LastRouteSwitchTime
	}
	return 0
}

type ListUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReq) Reset() {
	*x = ListUserReq{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReq) ProtoMessage() {}

func (x *ListUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReq.ProtoReflect.Descriptor instead.
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *ListUserReq) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListUserReq) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type ListUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResp) Reset() {
	*x = ListUserResp{}
	mi := &file_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResp) ProtoMessage() {}

func (x *ListUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResp.ProtoReflect.Descriptor instead.
func (*ListUserResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

func (x *ListUserResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUserResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetServerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Socks5Addr    string                 `protobuf:"bytes,1,opt,name=socks5_addr,json=socks5Addr,proto3" json:"socks5_addr,omitempty"`
	WsServerUrl   string                 `protobuf:"bytes,2,opt,name=ws_server_url,json=wsServerUrl,proto3" json:"ws_server_url,omitempty"`
	AccessSecret  string                 `protobuf:"bytes,3,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	AccessExpire  int64                  `protobuf:"varint,4,opt,name=access_expire,json=accessExpire,proto3" json:"access_expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResp) Reset() {
	*x = GetServerInfoResp{}
	mi := &file_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResp) ProtoMessage() {}

func (x *GetServerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResp.ProtoReflect.Descriptor instead.
func (*GetServerInfoResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17}
}

func (x *GetServerInfoResp) GetSocks5Addr() string {
	if x != nil {
		return x.Socks5Addr
	}
	return ""
}

func (x *GetServerInfoResp) GetWsServerUrl() string {
	if x != nil {
		return x.WsServerUrl
	}
	return ""
}

func (x *GetServerInfoResp) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *GetServerInfoResp) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

type GetNodeAccessTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeAccessTokenReq) Reset() {
	*x = GetNodeAccessTokenReq{}
	mi := &file_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeAccessTokenReq) ProtoMessage() {}

func (x *GetNodeAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeAccessTokenReq.ProtoReflect.Descriptor instead.
func (*GetNodeAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{18}
}

func (x *GetNodeAccessTokenReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeAccessTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeAccessTokenResp) Reset() {
	*x = GetNodeAccessTokenResp{}
	mi := &file_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeAccessTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeAccessTokenResp) ProtoMessage() {}

func (x *GetNodeAccessTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeAccessTokenResp.ProtoReflect.Descriptor instead.
func (*GetNodeAccessTokenResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{19}
}

func (x *GetNodeAccessTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpList        []string               `protobuf:"bytes,1,rep,name=ip_list,json=ipList,proto3" json:"ip_list,omitempty"` // max length 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistReq) Reset() {
	*x = AddBlacklistReq{}
	mi := &file_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistReq) ProtoMessage() {}

func (x *AddBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistReq.ProtoReflect.Descriptor instead.
func (*AddBlacklistReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{20}
}

func (x *AddBlacklistReq) GetIpList() []string {
	if x != nil {
		return x.IpList
	}
	return nil
}

type RemoveBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpList        []string               `protobuf:"bytes,1,rep,name=ip_list,json=ipList,proto3" json:"ip_list,omitempty"` // max length 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistReq) Reset() {
	*x = RemoveBlacklistReq{}
	mi := &file_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistReq) ProtoMessage() {}

func (x *RemoveBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistReq.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveBlacklistReq) GetIpList() []string {
	if x != nil {
		return x.IpList
	}
	return nil
}

type GetBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistReq) Reset() {
	*x = GetBlacklistReq{}
	mi := &file_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistReq) ProtoMessage() {}

func (x *GetBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistReq.ProtoReflect.Descriptor instead.
func (*GetBlacklistReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{22}
}

func (x *GetBlacklistReq) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetBlacklistReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetBlacklistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpList        []string               `protobuf:"bytes,1,rep,name=ip_list,json=ipList,proto3" json:"ip_list,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlacklistResp) Reset() {
	*x = GetBlacklistResp{}
	mi := &file_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlacklistResp) ProtoMessage() {}

func (x *GetBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlacklistResp.ProtoReflect.Descriptor instead.
func (*GetBlacklistResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{23}
}

func (x *GetBlacklistResp) GetIpList() []string {
	if x != nil {
		return x.IpList
	}
	return nil
}

func (x *GetBlacklistResp) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

type KickNodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNodeReq) Reset() {
	*x = KickNodeReq{}
	mi := &file_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNodeReq) ProtoMessage() {}

func (x *KickNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNodeReq.ProtoReflect.Descriptor instead.
func (*KickNodeReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{24}
}

func (x *KickNodeReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StatPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Bandwidth     int64                  `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Traffic       int64                  `protobuf:"varint,3,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPoint) Reset() {
	*x = StatPoint{}
	mi := &file_server_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPoint) ProtoMessage() {}

func (x *StatPoint) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPoint.ProtoReflect.Descriptor instead.
func (*StatPoint) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{25}
}

func (x *StatPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatPoint) GetBandwidth() int64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *StatPoint) GetTraffic() int64 {
	if x != nil {
		return x.Traffic
	}
	return 0
}

type AllStatsMinuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minutes       int32                  `protobuf:"varint,1,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllStatsMinuteReq) Reset() {
	*x = AllStatsMinuteReq{}
	mi := &file_server_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStatsMinuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStatsMinuteReq) ProtoMessage() {}

func (x *AllStatsMinuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStatsMinuteReq.ProtoReflect.Descriptor instead.
func (*AllStatsMinuteReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{26}
}

func (x *AllStatsMinuteReq) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type AllStatsHourReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllStatsHourReq) Reset() {
	*x = AllStatsHourReq{}
	mi := &file_server_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStatsHourReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStatsHourReq) ProtoMessage() {}

func (x *AllStatsHourReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStatsHourReq.ProtoReflect.Descriptor instead.
func (*AllStatsHourReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{27}
}

func (x *AllStatsHourReq) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type AllStatsDayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllStatsDayReq) Reset() {
	*x = AllStatsDayReq{}
	mi := &file_server_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStatsDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStatsDayReq) ProtoMessage() {}

func (x *AllStatsDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStatsDayReq.ProtoReflect.Descriptor instead.
func (*AllStatsDayReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{28}
}

func (x *AllStatsDayReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type StatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StatPoint           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResp) Reset() {
	*x = StatsResp{}
	mi := &file_server_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResp) ProtoMessage() {}

func (x *StatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResp.ProtoReflect.Descriptor instead.
func (*StatsResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{29}
}

func (x *StatsResp) GetStats() []*StatPoint {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UserStatsMinuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsMinuteReq) Reset() {
	*x = UserStatsMinuteReq{}
	mi := &file_server_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsMinuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsMinuteReq) ProtoMessage() {}

func (x *UserStatsMinuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsMinuteReq.ProtoReflect.Descriptor instead.
func (*UserStatsMinuteReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{30}
}

func (x *UserStatsMinuteReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStatsMinuteReq) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type UserStatsHourReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsHourReq) Reset() {
	*x = UserStatsHourReq{}
	mi := &file_server_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsHourReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsHourReq) ProtoMessage() {}

func (x *UserStatsHourReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsHourReq.ProtoReflect.Descriptor instead.
func (*UserStatsHourReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{31}
}

func (x *UserStatsHourReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStatsHourReq) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type UserStatsDayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsDayReq) Reset() {
	*x = UserStatsDayReq{}
	mi := &file_server_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsDayReq) ProtoMessage() {}

func (x *UserStatsDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsDayReq.ProtoReflect.Descriptor instead.
func (*UserStatsDayReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{32}
}

func (x *UserStatsDayReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStatsDayReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

// 获取一批指定用户的基础统计
type UserBaseStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBaseStatsReq) Reset() {
	*x = UserBaseStatsReq{}
	mi := &file_server_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBaseStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseStatsReq) ProtoMessage() {}

func (x *UserBaseStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseStatsReq.ProtoReflect.Descriptor instead.
func (*UserBaseStatsReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{33}
}

func (x *UserBaseStatsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserBaseStatsResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentBandwidth int64                  `protobuf:"varint,2,opt,name=current_bandwidth,json=currentBandwidth,proto3" json:"current_bandwidth,omitempty"`
	TopBandwidth     int64                  `protobuf:"varint,3,opt,name=top_bandwidth,json=topBandwidth,proto3" json:"top_bandwidth,omitempty"`
	TotalTraffic     int64                  `protobuf:"varint,4,opt,name=total_traffic,json=totalTraffic,proto3" json:"total_traffic,omitempty"`
	CurrentConns     int64                  `protobuf:"varint,5,opt,name=current_conns,json=currentConns,proto3" json:"current_conns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserBaseStatsResp) Reset() {
	*x = UserBaseStatsResp{}
	mi := &file_server_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBaseStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseStatsResp) ProtoMessage() {}

func (x *UserBaseStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseStatsResp.ProtoReflect.Descriptor instead.
func (*UserBaseStatsResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{34}
}

func (x *UserBaseStatsResp) GetCurrentBandwidth() int64 {
	if x != nil {
		return x.CurrentBandwidth
	}
	return 0
}

func (x *UserBaseStatsResp) GetTopBandwidth() int64 {
	if x != nil {
		return x.TopBandwidth
	}
	return 0
}

func (x *UserBaseStatsResp) GetTotalTraffic() int64 {
	if x != nil {
		return x.TotalTraffic
	}
	return 0
}

func (x *UserBaseStatsResp) GetCurrentConns() int64 {
	if x != nil {
		return x.CurrentConns
	}
	return 0
}

type UserStatChartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatChartReq) Reset() {
	*x = UserStatChartReq{}
	mi := &file_server_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatChartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatChartReq) ProtoMessage() {}

func (x *UserStatChartReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatChartReq.ProtoReflect.Descriptor instead.
func (*UserStatChartReq) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{35}
}

func (x *UserStatChartReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStatChartReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserStatChartReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UserStatChartReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type UserStatChartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*StatPoint           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatChartResp) Reset() {
	*x = UserStatChartResp{}
	mi := &file_server_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatChartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatChartResp) ProtoMessage() {}

func (x *UserStatChartResp) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatChartResp.ProtoReflect.Descriptor instead.
func (*UserStatChartResp) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{36}
}

func (x *UserStatChartResp) GetStats() []*StatPoint {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_server_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{37}
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\x1a\x1bgoogle/protobuf/empty.proto\"I\n" +
	"\vListNodeReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\"x\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1b\n" +
	"\tnet_delay\x18\x03 \x01(\x05R\bnetDelay\x12\x1b\n" +
	"\tbind_user\x18\x04 \x01(\tR\bbindUser\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\"H\n" +
	"\fListNodeResp\x12\"\n" +
	"\x05nodes\x18\x01 \x03(\v2\f.server.NodeR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8a\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12)\n" +
	"\x10interval_minutes\x18\x03 \x01(\x05R\x0fintervalMinutes\x12)\n" +
	"\x11utc_minute_of_day\x18\x04 \x01(\x05R\x0eutcMinuteOfDay\"m\n" +
	"\fTrafficLimit\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12#\n" +
	"\rtotal_traffic\x18\x03 \x01(\x03R\ftotalTraffic\"\x86\x02\n" +
	"\rCreateUserReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x129\n" +
	"\rtraffic_limit\x18\x03 \x01(\v2\x14.server.TrafficLimitR\ftrafficLimit\x12#\n" +
	"\x05route\x18\x04 \x01(\v2\r.server.RouteR\x05route\x12,\n" +
	"\x12upload_rate_limite\x18\x05 \x01(\x03R\x10uploadRateLimite\x12.\n" +
	"\x13download_rate_limit\x18\x06 \x01(\x03R\x11downloadRateLimit\"\x84\x02\n" +
	"\x0eCreateUserResp\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x129\n" +
	"\rtraffic_limit\x18\x02 \x01(\v2\x14.server.TrafficLimitR\ftrafficLimit\x12#\n" +
	"\x05route\x18\x03 \x01(\v2\r.server.RouteR\x05route\x12\x17\n" +
	"\anode_ip\x18\x04 \x01(\tR\x06nodeIp\x12,\n" +
	"\x12upload_rate_limite\x18\x05 \x01(\x03R\x10uploadRateLimite\x12.\n" +
	"\x13download_rate_limit\x18\x06 \x01(\x03R\x11downloadRateLimit\"F\n" +
	"\x11UserOperationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\"W\n" +
	"\x15ModifyUserPasswordReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x8c\x01\n" +
	"\rModifyUserReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x129\n" +
	"\rtraffic_limit\x18\x02 \x01(\v2\x14.server.TrafficLimitR\ftrafficLimit\x12#\n" +
	"\x05route\x18\x03 \x01(\v2\r.server.RouteR\x05route\")\n" +
	"\n" +
	"GetUserReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"N\n" +
	"\x16SwitchUserRouteNodeReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\",\n" +
	"\rDeleteUserReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"I\n" +
	"\x12StartOrStopUserReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\x8b\x03\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x129\n" +
	"\rtraffic_limit\x18\x02 \x01(\v2\x14.server.TrafficLimitR\ftrafficLimit\x12#\n" +
	"\x05route\x18\x03 \x01(\v2\r.server.RouteR\x05route\x12\x17\n" +
	"\anode_ip\x18\x04 \x01(\tR\x06nodeIp\x12\x1f\n" +
	"\vnode_online\x18\x05 \x01(\bR\n" +
	"nodeOnline\x12'\n" +
	"\x0fcurrent_traffic\x18\x06 \x01(\x03R\x0ecurrentTraffic\x12\x10\n" +
	"\x03off\x18\a \x01(\bR\x03off\x12,\n" +
	"\x12upload_rate_limite\x18\b \x01(\x03R\x10uploadRateLimite\x12.\n" +
	"\x13download_rate_limit\x18\t \x01(\x03R\x11downloadRateLimit\x123\n" +
	"\x16last_route_switch_time\x18\n" +
	" \x01(\x03R\x13lastRouteSwitchTime\"5\n" +
	"\vListUserReq\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"H\n" +
	"\fListUserResp\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.server.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa2\x01\n" +
	"\x11GetServerInfoResp\x12\x1f\n" +
	"\vsocks5_addr\x18\x01 \x01(\tR\n" +
	"socks5Addr\x12\"\n" +
	"\rws_server_url\x18\x02 \x01(\tR\vwsServerUrl\x12#\n" +
	"\raccess_secret\x18\x03 \x01(\tR\faccessSecret\x12#\n" +
	"\raccess_expire\x18\x04 \x01(\x03R\faccessExpire\"0\n" +
	"\x15GetNodeAccessTokenReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\".\n" +
	"\x16GetNodeAccessTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x0fAddBlacklistReq\x12\x17\n" +
	"\aip_list\x18\x01 \x03(\tR\x06ipList\"-\n" +
	"\x12RemoveBlacklistReq\x12\x17\n" +
	"\aip_list\x18\x01 \x03(\tR\x06ipList\"?\n" +
	"\x0fGetBlacklistReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"L\n" +
	"\x10GetBlacklistResp\x12\x17\n" +
	"\aip_list\x18\x01 \x03(\tR\x06ipList\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\"&\n" +
	"\vKickNodeReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"a\n" +
	"\tStatPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x03R\tbandwidth\x12\x18\n" +
	"\atraffic\x18\x03 \x01(\x03R\atraffic\"-\n" +
	"\x11AllStatsMinuteReq\x12\x18\n" +
	"\aminutes\x18\x01 \x01(\x05R\aminutes\"'\n" +
	"\x0fAllStatsHourReq\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\"$\n" +
	"\x0eAllStatsDayReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"4\n" +
	"\tStatsResp\x12'\n" +
	"\x05stats\x18\x01 \x03(\v2\x11.server.StatPointR\x05stats\"J\n" +
	"\x12UserStatsMinuteReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"D\n" +
	"\x10UserStatsHourReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\"A\n" +
	"\x0fUserStatsDayReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\".\n" +
	"\x10UserBaseStatsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xaf\x01\n" +
	"\x11UserBaseStatsResp\x12+\n" +
	"\x11current_bandwidth\x18\x02 \x01(\x03R\x10currentBandwidth\x12#\n" +
	"\rtop_bandwidth\x18\x03 \x01(\x03R\ftopBandwidth\x12#\n" +
	"\rtotal_traffic\x18\x04 \x01(\x03R\ftotalTraffic\x12#\n" +
	"\rcurrent_conns\x18\x05 \x01(\x03R\fcurrentConns\"|\n" +
	"\x10UserStatChartReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\"<\n" +
	"\x11UserStatChartResp\x12'\n" +
	"\x05stats\x18\x01 \x03(\v2\x11.server.StatPointR\x05stats\"\a\n" +
	"\x05Empty2\xfe\b\n" +
	"\tServerAPI\x125\n" +
	"\bListNode\x12\x13.server.ListNodeReq\x1a\x14.server.ListNodeResp\x12;\n" +
	"\n" +
	"CreateUser\x12\x15.server.CreateUserReq\x1a\x16.server.CreateUserResp\x125\n" +
	"\bListUser\x12\x13.server.ListUserReq\x1a\x14.server.ListUserResp\x12N\n" +
	"\x12ModifyUserPassword\x12\x1d.server.ModifyUserPasswordReq\x1a\x19.server.UserOperationResp\x12>\n" +
	"\n" +
	"ModifyUser\x12\x15.server.ModifyUserReq\x1a\x19.server.UserOperationResp\x12+\n" +
	"\aGetUser\x12\x12.server.GetUserReq\x1a\f.server.User\x12>\n" +
	"\n" +
	"DeleteUser\x12\x15.server.DeleteUserReq\x1a\x19.server.UserOperationResp\x12P\n" +
	"\x13SwitchUserRouteNode\x12\x1e.server.SwitchUserRouteNodeReq\x1a\x19.server.UserOperationResp\x12H\n" +
	"\x0fStartOrStopUser\x12\x1a.server.StartOrStopUserReq\x1a\x19.server.UserOperationResp\x129\n" +
	"\rGetServerInfo\x12\r.server.Empty\x1a\x19.server.GetServerInfoResp\x12S\n" +
	"\x12GetNodeAccessToken\x12\x1d.server.GetNodeAccessTokenReq\x1a\x1e.server.GetNodeAccessTokenResp\x12B\n" +
	"\fAddBlacklist\x12\x17.server.AddBlacklistReq\x1a\x19.server.UserOperationResp\x12H\n" +
	"\x0fRemoveBlacklist\x12\x1a.server.RemoveBlacklistReq\x1a\x19.server.UserOperationResp\x12A\n" +
	"\fGetBlacklist\x12\x17.server.GetBlacklistReq\x1a\x18.server.GetBlacklistResp\x12:\n" +
	"\bKickNode\x12\x13.server.KickNodeReq\x1a\x19.server.UserOperationResp\x12G\n" +
	"\x10GetUserBaseStats\x12\x18.server.UserBaseStatsReq\x1a\x19.server.UserBaseStatsResp\x12G\n" +
	"\x10GetUserStatChart\x12\x18.server.UserStatChartReq\x1a\x19.server.UserStatChartRespB\x06Z\x04./pbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_server_proto_goTypes = []any{
	(*ListNodeReq)(nil),            // 0: server.ListNodeReq
	(*Node)(nil),                   // 1: server.Node
	(*ListNodeResp)(nil),           // 2: server.ListNodeResp
	(*Route)(nil),                  // 3: server.Route
	(*TrafficLimit)(nil),           // 4: server.TrafficLimit
	(*CreateUserReq)(nil),          // 5: server.CreateUserReq
	(*CreateUserResp)(nil),         // 6: server.CreateUserResp
	(*UserOperationResp)(nil),      // 7: server.UserOperationResp
	(*ModifyUserPasswordReq)(nil),  // 8: server.ModifyUserPasswordReq
	(*ModifyUserReq)(nil),          // 9: server.ModifyUserReq
	(*GetUserReq)(nil),             // 10: server.GetUserReq
	(*SwitchUserRouteNodeReq)(nil), // 11: server.SwitchUserRouteNodeReq
	(*DeleteUserReq)(nil),          // 12: server.DeleteUserReq
	(*StartOrStopUserReq)(nil),     // 13: server.StartOrStopUserReq
	(*User)(nil),                   // 14: server.User
	(*ListUserReq)(nil),            // 15: server.ListUserReq
	(*ListUserResp)(nil),           // 16: server.ListUserResp
	(*GetServerInfoResp)(nil),      // 17: server.GetServerInfoResp
	(*GetNodeAccessTokenReq)(nil),  // 18: server.GetNodeAccessTokenReq
	(*GetNodeAccessTokenResp)(nil), // 19: server.GetNodeAccessTokenResp
	(*AddBlacklistReq)(nil),        // 20: server.AddBlacklistReq
	(*RemoveBlacklistReq)(nil),     // 21: server.RemoveBlacklistReq
	(*GetBlacklistReq)(nil),        // 22: server.GetBlacklistReq
	(*GetBlacklistResp)(nil),       // 23: server.GetBlacklistResp
	(*KickNodeReq)(nil),            // 24: server.KickNodeReq
	(*StatPoint)(nil),              // 25: server.StatPoint
	(*AllStatsMinuteReq)(nil),      // 26: server.AllStatsMinuteReq
	(*AllStatsHourReq)(nil),        // 27: server.AllStatsHourReq
	(*AllStatsDayReq)(nil),         // 28: server.AllStatsDayReq
	(*StatsResp)(nil),              // 29: server.StatsResp
	(*UserStatsMinuteReq)(nil),     // 30: server.UserStatsMinuteReq
	(*UserStatsHourReq)(nil),       // 31: server.UserStatsHourReq
	(*UserStatsDayReq)(nil),        // 32: server.UserStatsDayReq
	(*UserBaseStatsReq)(nil),       // 33: server.UserBaseStatsReq
	(*UserBaseStatsResp)(nil),      // 34: server.UserBaseStatsResp
	(*UserStatChartReq)(nil),       // 35: server.UserStatChartReq
	(*UserStatChartResp)(nil),      // 36: server.UserStatChartResp
	(*Empty)(nil),                  // 37: server.Empty
}
var file_server_proto_depIdxs = []int32{
	1,  // 0: server.ListNodeResp.nodes:type_name -> server.Node
	4,  // 1: server.CreateUserReq.traffic_limit:type_name -> server.TrafficLimit
	3,  // 2: server.CreateUserReq.route:type_name -> server.Route
	4,  // 3: server.CreateUserResp.traffic_limit:type_name -> server.TrafficLimit
	3,  // 4: server.CreateUserResp.route:type_name -> server.Route
	4,  // 5: server.ModifyUserReq.traffic_limit:type_name -> server.TrafficLimit
	3,  // 6: server.ModifyUserReq.route:type_name -> server.Route
	4,  // 7: server.User.traffic_limit:type_name -> server.TrafficLimit
	3,  // 8: server.User.route:type_name -> server.Route
	14, // 9: server.ListUserResp.users:type_name -> server.User
	25, // 10: server.StatsResp.stats:type_name -> server.StatPoint
	25, // 11: server.UserStatChartResp.stats:type_name -> server.StatPoint
	0,  // 12: server.ServerAPI.ListNode:input_type -> server.ListNodeReq
	5,  // 13: server.ServerAPI.CreateUser:input_type -> server.CreateUserReq
	15, // 14: server.ServerAPI.ListUser:input_type -> server.ListUserReq
	8,  // 15: server.ServerAPI.ModifyUserPassword:input_type -> server.ModifyUserPasswordReq
	9,  // 16: server.ServerAPI.ModifyUser:input_type -> server.ModifyUserReq
	10, // 17: server.ServerAPI.GetUser:input_type -> server.GetUserReq
	12, // 18: server.ServerAPI.DeleteUser:input_type -> server.DeleteUserReq
	11, // 19: server.ServerAPI.SwitchUserRouteNode:input_type -> server.SwitchUserRouteNodeReq
	13, // 20: server.ServerAPI.StartOrStopUser:input_type -> server.StartOrStopUserReq
	37, // 21: server.ServerAPI.GetServerInfo:input_type -> server.Empty
	18, // 22: server.ServerAPI.GetNodeAccessToken:input_type -> server.GetNodeAccessTokenReq
	20, // 23: server.ServerAPI.AddBlacklist:input_type -> server.AddBlacklistReq
	21, // 24: server.ServerAPI.RemoveBlacklist:input_type -> server.RemoveBlacklistReq
	22, // 25: server.ServerAPI.GetBlacklist:input_type -> server.GetBlacklistReq
	24, // 26: server.ServerAPI.KickNode:input_type -> server.KickNodeReq
	33, // 27: server.ServerAPI.GetUserBaseStats:input_type -> server.UserBaseStatsReq
	35, // 28: server.ServerAPI.GetUserStatChart:input_type -> server.UserStatChartReq
	2,  // 29: server.ServerAPI.ListNode:output_type -> server.ListNodeResp
	6,  // 30: server.ServerAPI.CreateUser:output_type -> server.CreateUserResp
	16, // 31: server.ServerAPI.ListUser:output_type -> server.ListUserResp
	7,  // 32: server.ServerAPI.ModifyUserPassword:output_type -> server.UserOperationResp
	7,  // 33: server.ServerAPI.ModifyUser:output_type -> server.UserOperationResp
	14, // 34: server.ServerAPI.GetUser:output_type -> server.User
	7,  // 35: server.ServerAPI.DeleteUser:output_type -> server.UserOperationResp
	7,  // 36: server.ServerAPI.SwitchUserRouteNode:output_type -> server.UserOperationResp
	7,  // 37: server.ServerAPI.StartOrStopUser:output_type -> server.UserOperationResp
	17, // 38: server.ServerAPI.GetServerInfo:output_type -> server.GetServerInfoResp
	19, // 39: server.ServerAPI.GetNodeAccessToken:output_type -> server.GetNodeAccessTokenResp
	7,  // 40: server.ServerAPI.AddBlacklist:output_type -> server.UserOperationResp
	7,  // 41: server.ServerAPI.RemoveBlacklist:output_type -> server.UserOperationResp
	23, // 42: server.ServerAPI.GetBlacklist:output_type -> server.GetBlacklistResp
	7,  // 43: server.ServerAPI.KickNode:output_type -> server.UserOperationResp
	34, // 44: server.ServerAPI.GetUserBaseStats:output_type -> server.UserBaseStatsResp
	36, // 45: server.ServerAPI.GetUserStatChart:output_type -> server.UserStatChartResp
	29, // [29:46] is the sub-list for method output_type
	12, // [12:29] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
