// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: server.proto

package serverapi

import (
	"context"

	"titan-ipoverlay/ippop/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBlacklistReq        = pb.AddBlacklistReq
	AllStatsDayReq         = pb.AllStatsDayReq
	AllStatsHourReq        = pb.AllStatsHourReq
	AllStatsMinuteReq      = pb.AllStatsMinuteReq
	CreateUserReq          = pb.CreateUserReq
	CreateUserResp         = pb.CreateUserResp
	DeleteUserReq          = pb.DeleteUserReq
	Empty                  = pb.Empty
	GetBlacklistReq        = pb.GetBlacklistReq
	GetBlacklistResp       = pb.GetBlacklistResp
	GetNodeAccessTokenReq  = pb.GetNodeAccessTokenReq
	GetNodeAccessTokenResp = pb.GetNodeAccessTokenResp
	GetServerInfoResp      = pb.GetServerInfoResp
	GetUserReq             = pb.GetUserReq
	KickNodeByIPReq        = pb.KickNodeByIPReq
	KickNodeReq            = pb.KickNodeReq
	ListNodeReq            = pb.ListNodeReq
	ListNodeResp           = pb.ListNodeResp
	ListUserReq            = pb.ListUserReq
	ListUserResp           = pb.ListUserResp
	ModifyUserPasswordReq  = pb.ModifyUserPasswordReq
	ModifyUserReq          = pb.ModifyUserReq
	Node                   = pb.Node
	RemoveBlacklistReq     = pb.RemoveBlacklistReq
	Route                  = pb.Route
	StartOrStopUserReq     = pb.StartOrStopUserReq
	StatPoint              = pb.StatPoint
	StatsResp              = pb.StatsResp
	SwitchUserRouteNodeReq = pb.SwitchUserRouteNodeReq
	TrafficLimit           = pb.TrafficLimit
	User                   = pb.User
	UserBaseStatsReq       = pb.UserBaseStatsReq
	UserBaseStatsResp      = pb.UserBaseStatsResp
	UserOperationResp      = pb.UserOperationResp
	UserStatChartReq       = pb.UserStatChartReq
	UserStatChartResp      = pb.UserStatChartResp
	UserStatsDayReq        = pb.UserStatsDayReq
	UserStatsHourReq       = pb.UserStatsHourReq
	UserStatsMinuteReq     = pb.UserStatsMinuteReq

	ServerAPI interface {
		ListNode(ctx context.Context, in *ListNodeReq, opts ...grpc.CallOption) (*ListNodeResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
		ModifyUserPassword(ctx context.Context, in *ModifyUserPasswordReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error)
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		SwitchUserRouteNode(ctx context.Context, in *SwitchUserRouteNodeReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		StartOrStopUser(ctx context.Context, in *StartOrStopUserReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		GetServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServerInfoResp, error)
		GetNodeAccessToken(ctx context.Context, in *GetNodeAccessTokenReq, opts ...grpc.CallOption) (*GetNodeAccessTokenResp, error)
		AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error)
		KickNode(ctx context.Context, in *KickNodeReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		KickNodeByIP(ctx context.Context, in *KickNodeByIPReq, opts ...grpc.CallOption) (*UserOperationResp, error)
		GetUserBaseStats(ctx context.Context, in *UserBaseStatsReq, opts ...grpc.CallOption) (*UserBaseStatsResp, error)
		GetUserStatChart(ctx context.Context, in *UserStatChartReq, opts ...grpc.CallOption) (*UserStatChartResp, error)
	}

	defaultServerAPI struct {
		cli zrpc.Client
	}
)

func NewServerAPI(cli zrpc.Client) ServerAPI {
	return &defaultServerAPI{
		cli: cli,
	}
}

func (m *defaultServerAPI) ListNode(ctx context.Context, in *ListNodeReq, opts ...grpc.CallOption) (*ListNodeResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.ListNode(ctx, in, opts...)
}

func (m *defaultServerAPI) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultServerAPI) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.ListUser(ctx, in, opts...)
}

func (m *defaultServerAPI) ModifyUserPassword(ctx context.Context, in *ModifyUserPasswordReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.ModifyUserPassword(ctx, in, opts...)
}

func (m *defaultServerAPI) ModifyUser(ctx context.Context, in *ModifyUserReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.ModifyUser(ctx, in, opts...)
}

func (m *defaultServerAPI) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultServerAPI) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultServerAPI) SwitchUserRouteNode(ctx context.Context, in *SwitchUserRouteNodeReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.SwitchUserRouteNode(ctx, in, opts...)
}

func (m *defaultServerAPI) StartOrStopUser(ctx context.Context, in *StartOrStopUserReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.StartOrStopUser(ctx, in, opts...)
}

func (m *defaultServerAPI) GetServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetServerInfoResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetServerInfo(ctx, in, opts...)
}

func (m *defaultServerAPI) GetNodeAccessToken(ctx context.Context, in *GetNodeAccessTokenReq, opts ...grpc.CallOption) (*GetNodeAccessTokenResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetNodeAccessToken(ctx, in, opts...)
}

func (m *defaultServerAPI) AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.AddBlacklist(ctx, in, opts...)
}

func (m *defaultServerAPI) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.RemoveBlacklist(ctx, in, opts...)
}

func (m *defaultServerAPI) GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetBlacklist(ctx, in, opts...)
}

func (m *defaultServerAPI) KickNode(ctx context.Context, in *KickNodeReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.KickNode(ctx, in, opts...)
}

func (m *defaultServerAPI) KickNodeByIP(ctx context.Context, in *KickNodeByIPReq, opts ...grpc.CallOption) (*UserOperationResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.KickNodeByIP(ctx, in, opts...)
}

func (m *defaultServerAPI) GetUserBaseStats(ctx context.Context, in *UserBaseStatsReq, opts ...grpc.CallOption) (*UserBaseStatsResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetUserBaseStats(ctx, in, opts...)
}

func (m *defaultServerAPI) GetUserStatChart(ctx context.Context, in *UserStatChartReq, opts ...grpc.CallOption) (*UserStatChartResp, error) {
	client := pb.NewServerAPIClient(m.cli.Conn())
	return client.GetUserStatChart(ctx, in, opts...)
}
