// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AccessTokenReq struct {
	NodeId string `form:"nodeid"`
}

type AccessTokenResp struct {
	Token string `json:"token"`
}

type AddBlackListReq struct {
	NodeID string `json:"node_id"`
}

type DeleteUserCache struct {
	UserName string `json:"user_name"`
}

type GetBlackListResp struct {
	Nodes []string `json:"nodes"`
}

type GetNodePopReq struct {
	NodeId string `form:"nodeid"`
}

type GetNodePopResp struct {
	ServerURL   string `json:"server_url"`
	AccessToken string `json:"access_token"`
}

type KickNodeReq struct {
	NodeID string `form:"nodeid"`
}

type NodeWSReq struct {
	NodeId  string `form:"id"`
	OS      string `form:"os"`
	Version string `form:"version,optional"`
}

type RemoveBlackListReq struct {
	NodeID string `json:"node_id"`
}

type ServerInfo struct {
	Socks5Addr   string `json:"socks5_addr"`
	WSServerURL  string `json:"ws_server_url"`
	AccessSecret string `json:"access_secret"`
	AccessExpire int64  `json:"access_expire"`
}

type WebWSReq struct {
	NodeId string `form:"id"`
	OS     string `form:"os"`
}
